# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:f9:57:1c:7d:5d:be:7b:81:ca:ff:27:9d:0a:b4:0e"
      - run:
          name: Run git-update.sh
          command: ssh ci@thatdamnqa.com "cd /srv/mancmetfeed2; ./git-update.sh"
    branches:
      only:
        - master
